"""empty message

Revision ID: 3144ed9707f8
Revises: None
Create Date: 2015-06-29 14:26:45.445649

"""

# revision identifiers, used by Alembic.
revision = '3144ed9707f8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['object.id'], ),
    sa.ForeignKeyConstraint(['loc_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.Column('loc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['object.id'], ),
    sa.ForeignKeyConstraint(['leader_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['loc_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('path',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['object.id'], ),
    sa.ForeignKeyConstraint(['nid'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pathpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('loc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loc_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['path_id'], ['path.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pathpoint')
    op.drop_table('path')
    op.drop_table('node')
    op.drop_table('point')
    op.drop_table('location')
    op.drop_table('object')
    ### end Alembic commands ###
