"""empty message

Revision ID: 4f25174a5732
Revises: 12fe07151f0
Create Date: 2015-06-22 13:39:10.104522

"""

# revision identifiers, used by Alembic.
revision = '4f25174a5732'
down_revision = '12fe07151f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
